site_name: py-allrecipes
repo_url: https://github.com/yourusername/py-allrecipes
repo_name: py-allrecipes
nav:
  - Home: index.md
  - Search & Recipe API: search.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details